<section>
    <h2>Programování</h2>
    <p>Pravidelně používám tyto technologie:</p>
    <ul class="seznam">
        <li><strong>HTML5</strong>, <strong>CSS3</strong> a responzivní webdesign </li>
        <li>Základní konstrukce a OOP v <strong>PHP</strong></li>
        <li><strong>MVC</strong> architektura v PHP</li>
        <li><strong>MySQL</strong></li>
    </ul>

    <p>Dále jsem se setkala (v rámci rekvalifikačního kurzu či samostudia):</p>
    <ul class="seznam">
        <li>Bootstrap</li>
        <li>JavaScript</li>
        <li>Java</li>
    </ul>

    <p>Používám tyto nástroje: Visual Studio Code, NetBeans, phpMyAdmin, GitHub.</p>
</section>

<section>
    <h2>Cizí jazyky</h2>
    <ul class="seznam">
        <li>
            <p><strong>Angličtina</strong> - komunikativně</p>
            <p>Využívám denně při sledování videí nebo čtení různých článků dle mých zájmů. V Anglii jsem strávila devět měsíců jako aupair, jazyk jsem tedy musela denně užívat i aktivně.</p>
        </li>
        <br>
        <li>
            <p><strong>Španělština</strong> - začátečník</p>
            <p>Učila jsem se čtyři roky na střední škole. Dlouho jsem španělštinu nepoužívala, ale věřím, že bych se na základní úrovni domluvila, pokud bych ji trochu oprášila:)</p>
        </li>
        <br>
        <li>
            <p><strong>Němčina</strong> - začátečník</p>
            <p>Začala jsem se učit během rodičovské dovolené za pomoci mobilních aplikací Duolingo a Memrise.</p>
        </li>
    </ul>
</section>