<div class="centrovac">
<p><img src="/pohledy/obrazky/email.png" alt="email" /></p>
<p>Chcete-li mě kontaktovat, napište mi na email<br> <strong>marikovamon (zavináč) seznam (tečka) cz</strong>.</p>
<p>Můžete mě kontaktovat i přes <a href="https://www.linkedin.com/in/monika-m-a18a481a8/" title="Můj LinkedIn profil">LinkedIn</a>.</p>
<p>Kódy mých projektů najdete na mém <a href="https://github.com/MonikaMarikova" title="Můj GitHub profil">GitHubu</a>.</p>
</div>