<h1 class="centrovac">Přihlášení do administrace</h1>

<form method="post">
<div class="prihlaseni">
        <label for="jmeno">Jméno</label>
        <input type="text" id="jmeno" name="jmeno" /><br />
    </div>
    <div class="prihlaseni">
        <label for="heslo">Heslo</label>
        <input type="password" id="heslo" name="heslo" /><br />
    </div>
    <input type="submit" value="Přihlásit" />
</form>

<p class="centrovac">Pokud ještě nemáte účet, <a href="registrace">zaregistrujte se</a>.</p>