<!DOCTYPE html>
<html lang="cs-cz">

<head>
    <base href="/localhost" />
    <meta charset="UTF-8" />
    <title><?= $titulek ?></title>
    <meta name="description" content="<?= $popis ?>" />
    <meta name="keywords" content="<?= $klicova_slova ?>" />
    <link rel="stylesheet" href="styl.css" type="text/css" />
</head>

<body>
    <header>
        <h1>Monika Mariková</h1>

        <nav class="menu">
            <ul>
                <li><a href="clanek/uvod">Úvod</a></li>
                <li><a href="clanek">Články</a></li>
                <li><a href="dovednosti">Dovednosti</a></li>
                <li><a href="kontakt">Kontakt</a></li>
            </ul>
        </nav>
    </header>

    <?php foreach ($zpravy as $zprava) : ?>
        <p class="zprava"><?= $zprava ?></p>
    <?php endforeach ?>
    
    <article>
        <?php $this->kontroler->vypisPohled(); // vložení aktuálního pohledu do šablony 
        ?>
    </article>

    <footer>
        <p>Vytvořila &copy;Monika Mariková 2023. <a href="administrace">Administrace</a>
        </p>
    </footer>
</body>

</html>